### ISSUE TITLE
Durable object instance not evicted when blockConcurrencyWhile() callback throws

### ISSUE THREAD

**Issue by broofa** [cloudflare/miniflare#378]
**Problem**
Chatting with @bretthoerner in Discord about how to force a DO to be evicted, he suggested throwing from within the `blockConcurrencyWhile()` callback.  While this works in production, it does not work in Miniflare.

**Current Behavior**
Miniflare logs the error as an Unhandled Promise Rejection, but does not destroy the DO instance.  (Subsequent DO requests go to the still-active instance rather than causing a new instance to be constructed).  Also, websocket connections that terminate at the DO remain open.

**Expected Behavior**
Unhandled errors in the `blockConcurrencyWhile()` should mirror the behavior in production.  I'm not sure what exactly this entails but, at a minimum, the DO instance should be destroyed such that a new instance is created by the next worker to reference the same DO id, and any associated websocket connections should be closed.

<img width="726" alt="CleanShot 2022-09-14 at 11 35 47@2x" src="https://user-images.githubusercontent.com/164050/190235238-13df441e-a342-4671-9f1f-e1f5e0e05043.png">

**Comment by penalosa** [comment]
Hey! Thanks for raising this issue! I'm going to close it for now since we haven't heard from you in a while, but if there's still outstanding questions feel free to comment with a minimal reproduction and we can open it again and investigate further. This is _probably_ fixed in Miniflare v3, which uses the open source Workers runtime (you can try it out with `wrangler dev --experimental-local`)

**Comment by penalosa** [comment]
Re-opening to track fixing this in Miniflare v2
