### ISSUE TITLE
Dependency "crypto": no matching module rules

### ISSUE THREAD

**Issue by benycodes** [cloudflare/miniflare#68]
Got an error when running my project which uses the Crypto API.
Any ideas how to resolve?

```
[mf:inf] Build succeeded
[mf:err] MiniflareError: Unable to resolve "dist\index.mjs" dependency "crypto": no matching module rules
```

**Comment by leviwolfe** [comment]
@benycodes did you solve your problem? I am running into the same problem. I bundle with Rollup and if I try to `import * as jose from 'jose';` using the https://github.com/panva/jose package, then I get the same error:

```
[mf:inf] Build succeeded
[mf:dbg] Reloading worker...
[mf:err] VMScriptRunnerError [ERR_MODULE_RULE]: Unable to resolve "dist\index.mjs" dependency "crypto": no matching module rules
```

**Comment by faisalil** [comment]
any luck on this issue? @leviwolfe and @benycodes ?

**Comment by leviwolfe** [comment]
@faisalil For my specific issue, I actually don't believe it was a Miniflare issue, just Miniflare telling me the problem. The error indicated that code was trying to load a "crypto" module. This was because [Rollup was grabbing the Node export from jose rather than the browser one](https://github.com/panva/jose/blob/main/package.json#L74-L78). For Cloudflare Workers, we need to be using the [Web Crypto API (crypto.subtle)](https://developers.cloudflare.com/workers/runtime-apis/web-crypto) not the [Node.js crypto module](https://nodejs.org/api/crypto.html). When I added browser conditions to `nodeResolve` in my rollup.config.js like this, the correct export was grabbed and I was able to use https://github.com/panva/jose:

```
plugins: [
	commonjs(),
	json(),
	nodeResolve({ browser: true, exportConditions: ['browser', 'worker'] }),
	terser(),
],
```
